name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: prof4sure/SimplDev
    - name: Build the Docker image
      run: |
        
        ls -a 
        docker build . 
        
